{{- range $.Values.models }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: {{ .rewriteTarget }}
spec:
  rules:
    - host: {{ $.Values.host }}
      http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: {{ .name }}
              servicePort: {{ .port }}

{{- end }}