{{- range $.Values.models }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      {{- if $.Values.regCredB64enc }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .port }}
        {{- if .env }}
        env: {{ toYaml .env | nindent 8}}
        {{- end }}
        {{- if .resources}}
        resources: {{ toYaml .resources | nindent 10}}
        {{- end}}
        {{- if (default false .healthcheck) }}
        startupProbe:
          httpGet:
            path: /healthz
            port: {{ .port }}
          failureThreshold: 30
          periodSeconds: 10
        {{- end }}
{{- end }}