host: sgnlp.aks.aisingapore.net

ui:
  name: ui
  port: 8080
  image: aisgk8sregistry.azurecr.io/sgnlp/sgnlp-ui:latest

models:
  lsr:
    name: lsr
    port: 8000
    path: /api/relation-extraction/lsr/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: aisgk8sregistry.azurecr.io/sgnlp/lsr:latest
    resources:
      requests:
        memory: "5Gi"
        cpu: "500m"
  ufd:
    name: ufd
    port: 8000
    path: /api/cross-lingual-cross-domain/ufd/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: aisgk8sregistry.azurecr.io/sgnlp/ufd:latest
    resources:
      requests:
        memory: "8Gi"
        cpu: "500m"
  recconSpanExtraction:
    name: span-extraction
    port: 8000
    path: /api/span-extraction/spanbert/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: aisgk8sregistry.azurecr.io/sgnlp/reccon-span-extraction:latest
    resources:
      requests:
        memory: "3Gi"
        cpu: "250m"
  recconEmotionEntailment:
    name: emotion-entailment
    port: 8000
    path: /api/emotion-entailment/roberta-base/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: aisgk8sregistry.azurecr.io/sgnlp/reccon-emotion-entailment:latest
    resources:
      requests:
        memory: "3Gi"
        cpu: "250m"
  nea:
    name: nea
    port: 8000
    path: /api/essay-scoring/nea/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: aisgk8sregistry.azurecr.io/sgnlp/nea:latest
    resources:
      requests:
        memory: "300Mi"
        cpu: "100m"
  lif3wayAp:
    name: lif-3way-ap
    port: 8000
    path: /api/identify-follow-up-question/lif-3way-ap/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: aisgk8sregistry.azurecr.io/sgnlp/lif-3way-ap:latest
    resources:
      requests:
        memory: "500Mi"
        cpu: "250m"