{{- if .Values.docs -}}
apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{ .Values.docs.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.docs.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.docs.name }}
        timestamp: "{{ now | unixEpoch }}"
    spec:
      {{- if .Values.regCredB64enc }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
      - name: {{ .Values.docs.name }}
        image: {{ .Values.docs.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.docs.port }}
          name: {{ .Values.docs.name }}
        {{- if .resources}}
        resources: {{ toYaml .Values.docs.resources | nindent 10}}
        {{- end}}
{{- end }}
